# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignup():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signup(self):
    self.driver.get("https://myih.telkom.co.id/")
    self.driver.set_window_size(1382, 744)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-6 > .btn-primary").click()
    self.driver.find_element(By.ID, "fullName").click()
    self.driver.find_element(By.ID, "fullName").send_keys("wiguna kurniawan")
    self.driver.find_element(By.ID, "mobileNumber").click()
    self.driver.find_element(By.ID, "mobileNumber").send_keys("0895372365465")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("wiguna28@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Bnm280494cv")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, "section > h1").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "section > h1").text == "Maaf, percobaan daftar akun gagal"
  
